#pragma once
#include "stockdatamodel.h"

class CBalance : public CFinanceReport
{
public:
	CBalance(void);
	//	因为 m_vec_index 中包含了指针，故重写 赋值函数和拷贝构造函数
	CBalance(const CBalance& rhs);
	CBalance& operator=(const CBalance& rhs);
	~CBalance(void);


	CStockDataModel * NewCopy();
	string GetDownloadUrl();
	int CheckReport(vector<string>&  arrayHeader, vector<vector<string>>&  arrayData);

private:
	void Initialize();

public:
	
	vector<double> m_vec_current_assets		;  //		"流动资产",                                      
	vector<double> m_vec_cash		;  //		"货币资金",                                      
	vector<double> m_vec_provision_of_settlement_fund		;  //		"结算备付金",                                    
	vector<double> m_vec_funds_lent		;  //		"拆出资金",                                      
	vector<double> m_vec_financial_assets_held_for_trading		;  //		"交易性金融资产",                                
	vector<double> m_vec_derivative_financial_assets		;  //		"衍生金融资产",                                  
	vector<double> m_vec_notes_receivable		;  //		"应收票据",                                      
	vector<double> m_vec_accounts_receivable		;  //		"应收账款",                                      
	vector<double> m_vec_advances_to_suppliers		;  //		"预付款项",                                      
	vector<double> m_vec_insurance_premiums_receivable		;  //		"应收保费",                                      
	vector<double> m_vec_cession_premiums_receivable		;  //		"应收分保账款",                                  
	vector<double> m_vec_provision_of_cession_receivable		;  //		"应收分保合同准备金",                            
	vector<double> m_vec_interests_receivable		;  //		"应收利息",                                      
	vector<double> m_vec_dividends_receivable		;  //		"应收股利",                                      
	vector<double> m_vec_other_receivable		;  //		"其他应收款",                                    
	vector<double> m_vec_export_tax_rebate		;  //		"应收出口退税",                                  
	vector<double> m_vec_subsidy_receivable		;  //		"应收补贴款",                                    
	vector<double> m_vec_receivable_deposit		;  //		"应收保证金",                                    
	vector<double> m_vec_internal_receivables		;  //		"内部应收款",                                    
	vector<double> m_vec_buying_and_selling_financial_assets		;  //		"买入返售金融资产",                              
	vector<double> m_vec_inventories		;  //		"存货",                                          
	vector<double> m_vec_deferred_expenses 		;  //		"待摊费用",                                      
	vector<double> m_vec_profit_and_loss_to_be_treated		;  //		"待处理流动资产损益",                            
	vector<double> m_vec_non_current_assets_maturing_within_one_year		;  //		"一年内到期的非流动资产",                        
	vector<double> m_vec_other_current_assets		;  //		"其他流动资产",                                  
	vector<double> m_vec_total_current_assets		;  //		"流动资产合计",                                  
	vector<double> m_vec_non_current_assets		;  //		"非流动资产",                                    
	vector<double> m_vec_loans_and_payments_on_behalf 		;  //		"发放贷款及垫款",                                
	vector<double> m_vec_available_for_sale_financial_assets		;  //		"可供出售金融资产",                              
	vector<double> m_vec_held_to_maturity_investments		;  //		"持有至到期投资",                                
	vector<double> m_vec_long_term_receivables		;  //		"长期应收款",                                    
	vector<double> m_vec_long_term_equity_investments		;  //		"长期股权投资",                                  
	vector<double> m_vec_other_long_term_investments		;  //		"其他长期投资",                                  
	vector<double> m_vec_investment_real_estates		;  //		"投资性房地产",                                  
	vector<double> m_vec_original_value_of_fixed_assets 		;  //		"固定资产原值",                                  
	vector<double> m_vec_accumulated_depreciation		;  //		"累计折旧",                                      
	vector<double> m_vec_fixed_assets_net_value		;  //		"固定资产净值",                                  
	vector<double> m_vec_fixed_assets_impairment_provision		;  //		"固定资产减值准备",                              
	vector<double> m_vec_fixed_assets_net_book_value		;  //		"固定资产净额",                                  
	vector<double> m_vec_construction_in_progress		;  //		"在建工程",                                      
	vector<double> m_vec_construction_supplies		;  //		"工程物资",                                      
	vector<double> m_vec_fixed_assets_pending_disposal		;  //		"固定资产清理",                                  
	vector<double> m_vec_bearer_biological_assets		;  //		"生产性生物资产",                                
	vector<double> m_vec_public_welfare_biological_assets		;  //		"公益性生物资产",                                
	vector<double> m_vec_oil_and_natural_gas_assets		;  //		"油气资产",                                      
	vector<double> m_vec_intangibel_assets		;  //		"无形资产",                                      
	vector<double> m_vec_research_and_development_costs		;  //		"开发支出",                                      
	vector<double> m_vec_goodwill		;  //		"商誉",                                          
	vector<double> m_vec_long_term_deferred_expenses		;  //		"长期待摊费用",                                  
	vector<double> m_vec_circulation_right_for_equity_separation 		;  //		"股权分置流通权",                                
	vector<double> m_vec_deferred_tax_assets		;  //		"递延所得税资产",                                
	vector<double> m_vec_other_non_current_assets		;  //		"其他非流动资产",                                
	vector<double> m_vec_total_non_current_assets		;  //		"非流动资产合计",                                
	vector<double> m_vec_total_assets		;  //		"资产总计",                                      
	vector<double> m_vec_current_debt		;  //		"流动负债",                                      
	vector<double> m_vec_short_term_borrowings		;  //		"短期借款",                                      
	vector<double> m_vec_borrowings_from_central_bank		;  //		"向中央银行借款",                                
	vector<double> m_vec_deposits_from_customers_and_interbank		;  //		"吸收存款及同业存放",                            
	vector<double> m_vec_deposit_funds		;  //		"拆入资金",                                      
	vector<double> m_vec_financial_assets_held_for_liabilities		;  //		"交易性金融负债",                                
	vector<double> m_vec_derivative_financial_liabilities		;  //		"衍生金融负债",                                  
	vector<double> m_vec_notes_payable		;  //		"应付票据",                                      
	vector<double> m_vec_accounts_payable		;  //		"应付账款",                                      
	vector<double> m_vec_advances_from_customers		;  //		"预收款项",                                      
	vector<double> m_vec_funds_from_sales_of_financial_assets_with_repurchasement_agreement		;  //		"卖出回购金融资产款",                            
	vector<double> m_vec_handling_charges_and_commissions_payable		;  //		"应付手续费及佣金",                              
	vector<double> m_vec_employee_benefits_payable		;  //		"应付职工薪酬",                                  
	vector<double> m_vec_taxes_and_surcharges_payable		;  //		"应交税费",                                      
	vector<double> m_vec_interests_payable		;  //		"应付利息",                                      
	vector<double> m_vec_dividends_payable		;  //		"应付股利",                                      
	vector<double> m_vec_other_accounts_payable		;  //		"其他应交款",                                    
	vector<double> m_vec_margin_payable		;  //		"应付保证金",                                    
	vector<double> m_vec_internal_accounts_payable		;  //		"内部应付款",                                    
	vector<double> m_vec_other_payables		;  //		"其他应付款",                                    
	vector<double> m_vec_accrued_expenses 		;  //		"预提费用",                                      
	vector<double> m_vec_expected_current_liabilities		;  //		"预计流动负债",                                  
	vector<double> m_vec_cession_insurance_premiums_payable		;  //		"应付分保账款",                                  
	vector<double> m_vec_provision_for_insurance_contracts		;  //		"保险合同准备金",                                
	vector<double> m_vec_funds_received_as_agent_of_stock_exchange 		;  //		"代理买卖证券款",                                
	vector<double> m_vec_funds_received_as_stock_underwrite		;  //		"代理承销证券款",                                
	vector<double> m_vec_international_ticket_clearing		;  //		"国际票证结算",                                  
	vector<double> m_vec_domestic_ticket_clearing		;  //		"国内票证结算",                                  
	vector<double> m_vec_deferred_income		;  //		"递延收益",                                      
	vector<double> m_vec_short_term_bonds_payable		;  //		"应付短期债券",                                  
	vector<double> m_vec_non_current_liabilities_maturing_within_one_year		;  //		"一年内到期的非流动负债",                        
	vector<double> m_vec_other_current_liablities		;  //		"其他流动负债",                                  
	vector<double> m_vec_total_current_liabilities		;  //		"流动负债合计",                                  
	vector<double> m_vec_non_current_liabilities		;  //		"非流动负债",                                    
	vector<double> m_vec_long_term_loans		;  //		"长期借款",                                      
	vector<double> m_vec_debentures_payable		;  //		"应付债券",                                      
	vector<double> m_vec_long_term_payables		;  //		"长期应付款",                                    
	vector<double> m_vec_specific_payable		;  //		"专项应付款",                                    
	vector<double> m_vec_expected_non_current_liabilities		;  //		"预计非流动负债",                                
	vector<double> m_vec_deferred_tax_liabilities		;  //		"递延所得税负债",                                
	vector<double> m_vec_other_non_current_liablities		;  //		"其他非流动负债",                                
	vector<double> m_vec_total_non_current_liabilities		;  //		"非流动负债合计",                                
	vector<double> m_vec_total_liability		;  //		"负债合计",                                      
	vector<double> m_vec_owners_equity		;  //		"所有者权益",                                    
	vector<double> m_vec_registered_capital		;  //		"实收资本(或股本)",                              
	vector<double> m_vec_capital_surplus		;  //		"资本公积",                                      
	vector<double> m_vec_treasury_stock		;  //		"库存股",                                        
	vector<double> m_vec_special_reserve		;  //		"专项储备",                                      
	vector<double> m_vec_surplus_reserve		;  //		"盈余公积",                                      
	vector<double> m_vec_provision_for_normal_risks		;  //		"一般风险准备",                                  
	vector<double> m_vec_not_sure_investment_losses		;  //		"未确定的投资损失",                              
	vector<double> m_vec_undistributed_profits		;  //		"未分配利润",                                    
	vector<double> m_vec_quasi_cash_dividend		;  //		"拟分配现金股利",                                
	vector<double> m_vec_exchange_differences_on_translating_foreign_operations 		;  //		"外币报表折算差额",                              
	vector<double> m_vec_total_owners_equity_belongs_to_parent_company		;  //		"归属于母公司股东权益合计",                      
	vector<double> m_vec_minority_interest		;  //		"少数股东权益",                                  
	vector<double> m_vec_total_owners_equity		;  //		"所有者权益(或股东权益)合计",                    
	vector<double> m_vec_total_liabilities_and_owners_equity		;  //		"负债和所有者权益(或股东权益)总计"               
	
};
