//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by GB28181ClientMDI.rc
//
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_GB28181ClientMDTYPE         130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define IDD_DIALOG_OUTPUT               201
#define IDC_STATIC_NAME                 207
#define IDC_STATIC_WND                  208
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define IDC_RECORD                      211
#define IDI_ICON_SOUND                  211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define IDC_CAPTURE                     212
#define IDI_ICON_RECORD                 212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define IDC_EFFECT                      213
#define IDI_ICON_STOPRECORD             213
#define ID_VIEW_APPLOOK_VS_2005         214
#define IDC_SOUND                       214
#define IDI_ICON_STOPPLAY               214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define IDC_STOPPLAY                    215
#define IDI_ICON_CAPTURE                215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define IDI_ICON_PARA                   216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define IDI_ICON_STOPSOUND              217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDR_MENU_FULL                   218
#define IDI_ICON_HUE_ADD                219
#define IDC_SATURATIONADD               220
#define IDI_ICON_HUE_DEC                220
#define IDC_BRIGHTADD                   221
#define IDI_ICON_SATR_ADD               221
#define IDC_BRIGHTDEC                   222
#define IDI_ICON_SATR_DEC               222
#define IDC_CONTRASTADD                 223
#define IDI_ICON_CON_ADD                223
#define IDC_CONTRASTDEC                 224
#define IDI_ICON_CON_DEC                224
#define IDC_VOLUMEDEC                   225
#define IDI_ICON_BRI_ADD                225
#define IDC_SATURATIONDEC               226
#define IDI_ICON_BRI_DEC                226
#define IDC_HUEADD                      227
#define IDC_TITLE                       228
#define IDC_HUEDEC                      228
#define IDC_VOLUMEADD                   229
#define IDB_PTZ_ZOOMOUT_DOWN            239
#define IDB_PTZ_ZOOMOUT                 240
#define IDB_PTZ_DOWN_DOWN               241
#define IDB_PTZ_DOWN                    242
#define IDB_PTZ_LEFT_DOWN               243
#define IDB_PTZ_LEFT                    244
#define IDB_PTZ_RIGHT_DOWN              245
#define IDB_PTZ_RIGHT                   246
#define IDB_PTZ_UP_DOWN                 247
#define IDB_PTZ_UP                      248
#define IDB_PTZ_ZOOMIN_DOWN             249
#define IDB_PTZ_ZOOMIN                  250
#define IDI_ICON_VOLUME_ADD             253
#define IDI_ICON_VOLUME_DEC             254
#define IDB_BITMAP_RECORD               255
#define IDB_BITMAP_CAPTURE              256
#define IDB_BITMAP_VIDEO                257
#define IDB_BITMAP_SOUND                258
#define IDB_BITMAP_CLOSE                259
#define IDI_ICON_CUR_RECORD             261
#define IDI_ICON_CUR_STOPRECORD         262
#define IDI_ICON_CUR_CAPTURE            263
#define IDI_ICON_CUR_SOUND              264
#define IDI_ICON_CUR_STOPSOUND          265
#define IDI_ICON_CUR_PARA               266
#define IDI_ICON_CUR_STOPPLAY           267
#define IDC_TOOLTIP                     270
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_REALPLAYVIEW                310
#define IDR_POPUP_CHANNEL               310
#define ID_VIEW_CATALOG                 311
#define IDD_CATALOGQUERYDLG             312
#define IDD_PLAYBACKVIEW                313
#define IDB_PLAYBACK                    1204
#define IDB_PLAY_N                      1205
#define IDB_PLAY_M                      1206
#define IDB_PLAY_D                      1207
#define IDB_CAPTURE_N                   1208
#define IDB_CAPTURE_M                   1209
#define IDB_CAPTURE_D                   1210
#define IDB_STOP_N                      1211
#define IDB_STOP_M                      1212
#define IDB_STOP_D                      1213
#define IDB_PAUSE_N                     1214
#define IDB_PAUSE_M                     1215
#define IDB_PAUSE_D                     1216
#define IDB_RECORD_N                    1217
#define IDB_RECORD_M                    1218
#define IDB_RECORD_D                    1219
#define IDB_DOWN_N                      1220
#define IDB_DOWN_M                      1221
#define IDB_DOWN_D                      1222
#define IDB_ONE_N                       1223
#define IDB_ONE_M                       1224
#define IDB_ONE_D                       1225
#define IDB_FOUR_N                      1226
#define IDB_FOUR_M                      1227
#define IDB_FOUR_D                      1228
#define IDB_FULLSCREEN_N                1229
#define IDB_FULLSCREEN_M                1230
#define IDB_FULLSCREEN_D                1231
#define IDB_ONEBYONE_N                  1232
#define IDB_ONEBYONE_M                  1233
#define IDB_ONEBYONE_D                  1234
#define IDB_VOICE_N                     1235
#define IDB_VOICE_M                     1236
#define IDB_VOICECLOSE_N                1238
#define IDB_VOICECLOSE_M                1239
#define IDB_BTNS_BACKGROUND             1241
#define IDB_BTNS_SEP                    1242
#define IDB_SPEED_TEXT                  1243
#define IDB_SPEED_BK_N                  1244
#define IDB_SPEED_THUMB_N               1245
#define IDB_HIDE_N                      1246
#define IDB_HIDE_M                      1247
#define IDB_HIDE_D                      1248
#define IDB_SHOW_N                      1249
#define IDB_SHOW_M                      1250
#define IDB_SHOW_D                      1251
#define IDB_STOP_RECORD_N               1252
#define IDB_STOP_RECORD_M               1253
#define IDB_STOP_RECORD_D               1254
#define IDB_FIND_N                      1255
#define IDB_FIND_D                      1256
#define IDM_FULL_SCREEN                 32768
#define IDM_REGION_ZOOM                 32769
#define ID_32771                        32771
#define ID_REALPLAY                     32772
#define ID_32773                        32773
#define ID_SHOW_RATIO_4_3               32773
#define ID_PLAYBACK                     32774
#define ID_SHOW_RATIO_16_9              32774
#define ID_SHOW_RATIO_FULL              32775
#define ID_32775                        32775
#define ID_Alarm_Subscribe              32776

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        311
#define _APS_NEXT_COMMAND_VALUE         32777
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           314
#endif
#endif
